### ISSUE TITLE
Runtime error when running on linux

### ISSUE THREAD

**Issue by DerfOh** [Moonlington/FloSelfbot#34]
Hello, I'm getting the following error when running the bot on Linux with the latest release, after executing the help command it seems to crash with the following error.

```
derfoh@botserv:~$ ./FloSelfbot_LINUX
2017/10/15 13:50:55 [DG0] wsapi.go:434:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field Channel.type of type string
Login successful. (Took 0.36 seconds)
Logged onto 16 guilds.

FloSelfbot is now running.
Type .help to see all commands!
Press CTRL-C to exit.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x82df14]

goroutine 87 [running]:
main.messageCreate(0xc4201380f0, 0xc42000c1b0)
        C:/Users/Gebruiker/Desktop/Languages/Go/src/github.com/Moonlington/FloSelfbot/bot.go:265 +0x504
github.com/Moonlington/FloSelfbot/vendor/github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x935e88, 0xc4201380f0, 0x895ca0, 0xc42000c1b0)
        C:/Users/Gebruiker/Desktop/Languages/Go/src/github.com/Moonlington/FloSelfbot/vendor/github.com/bwmarrin/discordgo/eventhandlers.go:494 +0x57
created by github.com/Moonlington/FloSelfbot/vendor/github.com/bwmarrin/discordgo.(*Session).handle
        C:/Users/Gebruiker/Desktop/Languages/Go/src/github.com/Moonlington/FloSelfbot/vendor/github.com/bwmarrin/discordgo/event.go:159 +0xc2
```

When attempting a source build from the latest commit and via docker I get the following:
```
derfoh@botserv:~$ go get -u github.com/Moonlington/FloSelfbot
# github.com/Moonlington/FloSelfbot/commands
work/src/github.com/Moonlington/FloSelfbot/commands/channelinfo.go:17:17: ctx.Channel.IsPrivate undefined (type *discordgo.Channel has no field or method IsPrivate)
work/src/github.com/Moonlington/FloSelfbot/commands/channelinfo.go:29:9: cannot use ctx.Channel.Type (type discordgo.ChannelType) as type string in field value
work/src/github.com/Moonlington/FloSelfbot/commands/channelinfo.go:73:51: ctx.Channel.Recipient undefined (type *discordgo.Channel has no field or method Recipient)
work/src/github.com/Moonlington/FloSelfbot/commands/highlight.go:58:22: ch.IsPrivate undefined (type *discordgo.Channel has no field or method IsPrivate)
work/src/github.com/Moonlington/FloSelfbot/commands/highlight.go:70:7: ch.IsPrivate undefined (type *discordgo.Channel has no field or method IsPrivate)
work/src/github.com/Moonlington/FloSelfbot/commands/highlight.go:71:43: ch.Recipient undefined (type *discordgo.Channel has no field or method Recipient)
work/src/github.com/Moonlington/FloSelfbot/commands/highlight.go:81:8: ch.IsPrivate undefined (type *discordgo.Channel has no field or method IsPrivate)
work/src/github.com/Moonlington/FloSelfbot/commands/quote.go:43:17: ctx.Channel.IsPrivate undefined (type *discordgo.Channel has no field or method IsPrivate)
work/src/github.com/Moonlington/FloSelfbot/commands/quote.go:95:10: c.Recipient undefined (type *discordgo.Channel has no field or method Recipient)
work/src/github.com/Moonlington/FloSelfbot/commands/quote.go:117:23: ch.IsPrivate undefined (type *discordgo.Channel has no field or method IsPrivate)
work/src/github.com/Moonlington/FloSelfbot/commands/quote.go:117:23: too many errors
```

**Comment by DerfOh** [comment]
This might be due to #33 not sure, since the update is needed though I'll close this.
